language: ruby
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake spec'
bundler_args: --without system_tests
  rvm:
    2.3
matrix:
  fast_finish: true
  include:
    - env: PUPPET_VERSION="~> 4.8.2"
    - env: PUPPET_VERSION="~> 5.0"
    - env: PUPPET_VERSION="~> 6.0"
